### ISSUE TITLE
" Error: Cannot automatically retrieve the term names by the input ID ...."

### ISSUE THREAD

**Issue by joey0214** [jokergoo/KeywordsEnrichment#1]
Hi, Zuguang, 

This is a marvelous function! Great job! 

I got an error from the function. see below
Perform over-representation analysis on group 'set7', 14 genes...
```
Use column 'ID' as `go_id_column`.
Use column 'p.adjust' as `padj_column`.
 Error: Cannot automatically retrieve the term names by the input ID, please set values for
`term` argument manually. 
```
according to the TractBack hit, it seems first stop at "anno_word_cloud_from_GO(split, go_list, ...) at anno.R#91"

Do you have any clue for this error? i can send you data via email if you want to reproduce the error. 

Best regards,
Xiangfu

**Comment by jokergoo** [comment]
Can you send me your data? This function is quite young and needs more test.
